#!/usr/bin/env python

# serverless database query - sparql example

# Copyright 2016 Amazon.com, Inc. or its affiliates.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#    http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file.
# This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions
# and limitations under the License.

from SPARQLWrapper import SPARQLWrapper, JSON
import logging
import traceback
from os import environ

endpoint=environ.get('ENDPOINT')
port=environ.get('PORT')

baseURI="http://{0}:{1}/sparql".format(endpoint,port)

query="""
    SELECT ?hello ?world
    WHERE { GRAPH  <amzn://serverless_test>  { ?s ?hello ?world } }
    """

logger=logging.getLogger()
logger.setLevel(logging.INFO)

def sparql_config():
    cfg=SPARQLWrapper(baseURI)
    cfg.setQuery(query)
    cfg.setReturnFormat(JSON)
    return cfg


def log_err(errmsg):
    logger.error(errmsg)
    return {"body": errmsg , "headers": {}, "statusCode": 400,
        "isBase64Encoded":"false"}

try:
    sparql=sparql_config() 
    logger.info("Cold start complete.")
except:
    exit(log_err ("\nERROR: Cold start failed.\n{}".format (
       traceback.format_exc())))  


def handler(event,context):

    try:
        results=sparql.query().convert()
    except:
        conn_info='\nEndpoint: {0}\nPort: {1}\n'.format(endpoint, port)
        logger.error(conn_info)
        return log_err("ERROR: Cannot execute sparql query.\n{}".format(
            traceback.format_exc()))

    try:
        results_list=[]
        for result in results["results"]["bindings"]:
            results_list.append("%s , %s" % (result['hello']['value'], result['world']['value']))
        print(results_list)
    except:
        return log_err ("ERROR: Cannot retrieve query data.\n{}".format(
            traceback.format_exc()))


    return {"body": str(results_list), "headers": {}, "statusCode": 200,
        "isBase64Encoded":"false"}

if __name__== "__main__":
    handler(None,None)

