#!/usr/bin/env python

# serverless database query - sparql example

# Copyright 2016 Amazon.com, Inc. or its affiliates.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#    http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file.
# This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions
# and limitations under the License.

from SPARQLWrapper import SPARQLWrapper, JSON
import logging
import traceback
from os import environ

endpoint=environ.get('ENDPOINT')
port=environ.get('PORT')

baseURI="http://{0}:{1}/sparql".format(endpoint,port)

query="""
    SELECT ?hello ?world
    WHERE { GRAPH  <amzn://serverless_test>  { ?s ?hello ?world } }
    """

logger=logging.getLogger()
logger.setLevel(logging.INFO)

def make_connection():
    cnx=SPARQLWrapper(baseURI)
    cnx.setQuery(query)
    cnx.setReturnFormat(JSON)
    return cnx


def log_err(errmsg):
    logger.error(errmsg)
    return {"body": errmsg , "headers": {}, "statusCode": 400,
        "isBase64Encoded":"false"}

try:
    sparql = make_connection()
    logger.info("Cold start complete.")
except:
    conn_info='Endpoint: {0}\nPort: {1}\nDbUser: {2}\nPassword: *******\nDatabase={3}\n'.format(
        endpoint, port, dbuser, database)
    logger.error("\nERROR: Cannot connect to database from outside handler.\n{0}\n{1}\n".format(
        conn_info, traceback.format_exc()))

def handler(event,context):

    global sparql

    try:
        results=sparql.query().convert()
    except:
        try:
            sparql = make_connection()
            logger.info("Database connection lost. Re-connected from inside handler.")
        except:
            return log_err("ERROR: Cannot connect to database from inside handler.\n{}".format(
                traceback.format_exc()))
        try:
            results=sparql.query().convert()
        except:
            return log_err ("ERROR: Cannot execute sparql query.\n{}".format(
                traceback.format_exc()) )

    try:
        results_list=[]
        for result in results["results"]["bindings"]:
            results_list.append("%s , %s" % (result['hello']['value'], result['world']['value']))
        print(results_list)
    except:
        return log_err ("ERROR: Cannot retrieve query data.\n{}".format(
            traceback.format_exc()))


    return {"body": str(results_list), "headers": {}, "statusCode": 200,
        "isBase64Encoded":"false"}

if __name__== "__main__":
    handler(None,None)

